version: '3.8'
services:
  node16:
    container_name: nodejs_16-alpine
    image: node:16-alpine
    volumes:
      - n16_files:/static
    restart: always
    command: sh
    tty: true

volumes:
  n16_files:
    driver: local